src/config/urls.py
from django.contrib import admin
from django.urls import path, include

from students.views import index

urlpatterns = [
    path("index/", index, name="index"),
    path("admin/", admin.site.urls),
    path("students/", include("students.urls")),
    path("groups/", include("groups.urls")),
    path("teachers/", include("teachers.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

src/students/urls.py
from django.urls import path

from students.views import (
    index,
    get_students,
    create_student,
    update_student,
    delete_student,
    students_error_404,
)

app_name = "students"

urlpatterns = [
    path("index/", index, name="index"),
    path("", get_students, name="get_students"),
    path("create/", create_student, name="create_student"),
    path("update/<int:pk>/", update_student, name="update_student"),
    path("delete/<int:pk>/", delete_student, name="delete_student"),
    path("__debug__/", students_error_404, name="students_error_404"),
]

src/students/models.py
import datetime
import random

from django.core.validators import MinLengthValidator
from django.db import models
from faker import Faker

from students.utils.validators import first_name_validator


class Student(models.Model):
    first_name = models.CharField(
        max_length=120,
        blank=True,
        null=True,
        validators=[MinLengthValidator(3), first_name_validator],
    )
    last_name = models.CharField(max_length=120, blank=True, null=True)
    email = models.EmailField(max_length=120)
    grade = models.PositiveSmallIntegerField(null=True, default=0)
    birth_date = models.DateField(null=True)

    def age(self):
        return datetime.datetime.now().year - self.birth_date.year

    def __str__(self):
        return f"{self.first_name}_{self.last_name} {self.email} ({self.id})"

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        for _ in range(count):
            cls.objects.create(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                grade=random.choice(range(1, 12)),
                birth_date=faker.date_time_between(start_date="-40y", end_date="-18y"),
            )

src/students/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from students.models import Student


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = ("first_name", "last_name", "email", "grade")

    @staticmethod
    def normalize_text(text: str) -> str:
        return text.strip().capitalize()

    def clean_email(self):
        email = self.cleaned_data["email"]

        if "@yandex" in email.lower():
            raise ValidationError("Yandex email is forbidden to use in our country!!!")

        return email

    def clean_last_name(self):
        return self.normalize_text(self.cleaned_data["last_name"])

    def clean_first_name(self):
        return self.normalize_text(self.cleaned_data["first_name"])

    def clean(self):
        cleaned_data = super().clean()

        first_name = cleaned_data["first_name"]
        last_name = cleaned_data["last_name"]

        if first_name == last_name:
            raise ValidationError("First_name and last_name cant be equal!!")

        return cleaned_data

src/students/views.py
from django.db.models import Q
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from webargs import fields
from webargs.djangoparser import use_args

from students.forms import StudentForm
from students.models import Student


def index(request: HttpRequest) -> HttpResponse:
    return render(request, template_name="index.html", context={"key": "Oksana"})


@use_args(
    {
        "first_name": fields.Str(required=False),
        "last_name": fields.Str(required=False),
        "search_text": fields.Str(required=False),
    },
    location="query",
)
def get_students(request: HttpRequest, params) -> HttpResponse:
    students = Student.objects.all()

    search_fields = ["last_name", "first_name", "email"]

    for name, value in params.items():
        if name == "search_text":
            or_filter = Q()
            for field in search_fields:
                or_filter |= Q(**{f"{field}__icontains": value})
            students = students.filter(or_filter)

        else:
            students = students.filter(**{name: value})

    # result = format_records(students)
    return render(
        request, template_name="students/list.html", context={"students": students}
    )


@csrf_exempt
def create_student(request: HttpRequest) -> HttpResponse:
    # form = """<form method="post">
    # <label for="FirstNameId">First name:</label><br>
    # <input type="text" id="FirstNameId" name="first_name" placeholder="Mikhailo" value="Student"><br>

    # <label for="LastNameId">Last name:</label><br>
    # <input type="text" id="LastNameId" name="last_name" placeholder="Lazoryk" value="Student"><br>

    # <label for="EmailId">Email:</label><br>
    #  <input type="email" id="EmailId" name="email" placeholder="admin@admin.com" value="admin@admi.com"><br>

    # <label for="GradeId">Grade:</label><br>
    # <input type="number" id="GradeId" name="grade" placeholder="100" value=100><br>

    # <button type="submit" value="Submit">Create</button>
    # </form>
    # """

    if request.method == "POST":
        form = StudentForm(request.POST)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("students:get_students"))

    elif request.method == "GET":
        form = StudentForm()

    return render(request, template_name="students/create.html", context={"form": form})


@csrf_exempt
def update_student(request: HttpRequest, pk: int) -> HttpResponse:
    student = get_object_or_404(Student.objects.all(), pk=pk)

    if request.method == "POST":
        form = StudentForm(request.POST, instance=student)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("students:get_students"))
    elif request.method == "GET":
        form = StudentForm(instance=student)

    return render(request, template_name="students/update.html", context={"form": form})


@csrf_exempt
def delete_student(request: HttpRequest, pk: int) -> HttpResponse:
    student = get_object_or_404(Student.objects.all(), pk=pk)
    if request.method == "POST":
        form = StudentForm(request.POST, instance=student)
        if form.is_valid():
            form.delete()
            return HttpResponse(f"student delete: {student}", status=404)
    elif request.method == "GET":
        form = StudentForm(instance=student)

    return render(request, template_name="students/delete.html", context={"form": form})


def students_error_404(request, exception):
    return render(request, template_name="system_errors/404_errors.html", status=404)

src/templates/students/create.html
{% extends "index.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST" style="width: 25em;margin: auto">
        {{ form|crispy }}
        <button type="submit" class="btn btn-success" value="Create">Create student</button>
    </form>

{% endblock content %}

src/templates/students/delete.html
{% extends "index.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST" style="width: 25em;margin: auto">
        {{ form|crispy }}
        <button type="submit" class="btn btn-success" value="Delete">Delete student</button>
    </form>

{% endblock content %}

src/templates/students/list.html
{% extends "index.html" %}
{% block content %}
    <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">First name</th>
            <th scope="col">Last nam</th>
            <th scope="col">Email</th>
            <th scope="col">Grade</th>
            <th scope="col">Birth date</th>
            <th scope="col">Age</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for student in students %}
            <tr>
                <th scope="row">{{ student.pk }}</th>
                <td>{{ student.first_name }}</td>
                <td>{{ student.last_name }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.grade }}</td>
                <td>{{ student.birth_date|default:"Unknown" }}</td>
                {% if student.birth_date %}
                    <td>{{ student.age }}</td>
                {% else %}
                    <td>Unknown age</td>
                {% endif %}
                <th>
                    <a type="button" class="btn btn-warning"
                       href="{% url 'students:update_student' student.pk %}"
                    >Edit</a>
                </th>
                <th>
                    <a type="button" class="btn btn-primary"
                       href="{% url 'students:delete_student' student.pk %}"
                    >Delete</a>
                </th>
            </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock content %}

src/templates/students/update.html
{% extends "index.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST" style="width: 25em;margin: auto">
        {{ form|crispy }}
        <button type="submit" class="btn btn-success" value="Update">Update student</button>
    </form>

{% endblock content %}